[package]
name = "osm"
version = "0.1.0"
authors = ["Erich Gubler <erichdongubler@gmail.com>"]
edition = "2018"

[dependencies]
osmpbfreader = "0.13.2"
structopt = "0.2.12"
roxmltree = "0.7.3"
version-compare = "0.0.6"
